-- Conversations table schema
-- Stores all messages and interactions within tickets
-- Last updated: 2024-01-10

CREATE TABLE conversations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    ticket_id UUID REFERENCES tickets(id),
    sender_id UUID REFERENCES users(id),
    message_type VARCHAR(20) CHECK (message_type IN (
        'customer', 'agent', 'ai_response', 'ai_suggestion', 'system'
    )),
    content TEXT NOT NULL,
    ai_generated BOOLEAN DEFAULT false,
    ai_confidence FLOAT,
    metadata JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    is_internal BOOLEAN DEFAULT false
);

-- Indexes
CREATE INDEX idx_conversations_ticket ON conversations(ticket_id);
CREATE INDEX idx_conversations_sender ON conversations(sender_id);
CREATE INDEX idx_conversations_type ON conversations(message_type);

-- Comments
COMMENT ON TABLE conversations IS 'All messages and interactions within support tickets';
COMMENT ON COLUMN conversations.message_type IS 'Type of message: customer inquiry, agent response, AI suggestion, etc.';
COMMENT ON COLUMN conversations.ai_generated IS 'Whether this message was generated by AI';
COMMENT ON COLUMN conversations.ai_confidence IS 'Confidence score for AI-generated responses';
COMMENT ON COLUMN conversations.is_internal IS 'Whether this is an internal note not visible to customers'; 